version: '3.8'
name: hardgg
services:
  app:
    container_name: hardgg-container
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9581:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  data-loader:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: ["node", "scripts/load-data.js"]
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
