version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING_INTERVAL=1000
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app:cached
      - /app/node_modules
      - /app/.next
      - /app/.turbo
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  data-loader:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: ["node", "scripts/load-data.mjs"]
    volumes:
      - .:/app:cached
      - /app/node_modules
      - ./results:/app/results:ro
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
